# Generated by Django 3.2.7 on 2021-10-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Producto', models.CharField(max_length=200)),
                ('Costo', models.IntegerField()),
                ('Cantidad', models.PositiveIntegerField(default=1)),
                ('Descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
